# Example config file

# Global options
verbose = false
debug = false # Useful for debugging

# Client options
[client]
scheme = "http" # [http, https]
host = "127.0.0.1"
port = 9292
path = "/"
connect_timeout = 5
inactivity_timeout = 5
  [client.cli]
  mode = "line" # [line, char] - line by line output or char by char
  dry_run = false # When true the command is run but not sent to the server
  [client.server]  # The settings in this section identify the hub 
                   # server that the minicron client should connect to when
                   # running `minicron run` on a client instance/machine/VM.
  scheme = "http" # [http, https]
  host = "127.0.0.1"
  port = 9292
  path = "/"
  

# Server options
[server]
host = "127.0.0.1"
port = 9292
path = "/"
pid_file = "/tmp/minicron.pid"
cron_file = "/etc/crontab"
  [server.session]
  name = "minicron.session"
  domain = "127.0.0.1"
  path = "/"
  ttl = 86400
  secret = "change_me"
  [server.database]
  type = "sqlite" # [mysql, postgresql, sqlite]
  # The options below are for mysql and postgresql only
  # host = "127.0.0.1"
  # database = "minicron"
  # username = "minicron"
  # password = "password"
  [server.ssh]
  connect_timeout = 10

# Alerting options
[alerts]
  [alerts.email]
  enabled = false
  # from = "from@example.com" # "Your Name <from@example.com>" syntax is also supported
  # to = "to@example.com"
    [alerts.email.smtp]
    address = "localhost" # "smtp.gmail.com" for gmail
    port = 25 # 587 for gmail
    # domain = "your.domain.name"
    # user_name = "username@email.com"
    # password = "password"
    # authentication = "plain"
    enable_starttls_auto = true

  [alerts.sms]
  enabled = false
  # from = "+442222222222"
  # to = "+443333333333"
    [alerts.sms.twilio]
    # account_sid = "YOUR_TWILIO_ACCOUNT_SID"
    # auth_token = "YOUR_TWILIO_AUTH_TOKEN"

  [alerts.pagerduty]
  enabled = false
  # service_key = "YOUR_PAGERDUTY_SERVICE_KEY"

  [alerts.aws_sns]
  enabled = false
  # secret_access_key = "YOUR_SECRET_ACCESS_KEY"
  # access_key_id = "YOUR_ACCESS_KEY_ID"
  # region = "AWS_REGION"
  # topic_arn = "YOUR_SNS_TOPIC_ARN"
