# Test valid config file

# Global options
verbose = false
debug = false

# Client options
[client]
  [client.server]
  scheme = "http" # [http, https]
  host = "127.0.0.1"
  # username = "username" # optional for basic auth
  # password = "password" # optional for basic auth
  port = 9292
  path = "/"
  connect_timeout = 5
  inactivity_timeout = 5
  # CLI options
  [client.cli]
  dry_run = false

# Server options
[server]
host = "127.0.0.1"
port = 9292
path = "/"
pid_file = "/tmp/minicron.pid"
timezone = "UTC"
  [server.session]
  name = "minicron.session"
  domain = "127.0.0.1"
  path = "/"
  ttl = 86400
  secret = "change_me"
  [server.database]
  type = "sqlite" # [mysql, postgresql, sqlite]
  # The options below are for mysql and postgresql only
  # host = "127.0.0.1"
  # database = "minicron"
  # username = "minicron"
  # password = "password"

# Alerting options
[alerts]
  [alerts.email]
  enabled = false
      [alerts.email.smtp]
      address = "localhost"
      port = 25

  [alerts.sms]
  enabled = false

  [alerts.pagerduty]
  enabled = false

  [alerts.aws_sns]
  enabled = false

  [alerts.slack]
  enabled = false
