# Test valid config file

# Global options
verbose = false
debug = false

# Client options
[client]
  dry_run = false
  [client.api]
  base_url = "http://127.0.0.1:9292/api/1.0"

# Server options
[server]
host = "127.0.0.1"
port = 9292
path = "/"
pid_file = "/tmp/minicron.pid"
timezone = "UTC"
  [server.session]
  name = "minicron.session"
  domain = "127.0.0.1"
  path = "/"
  ttl = 86400
  secret = "change_me"
  [server.database]
  type = "sqlite" # [mysql, postgresql, sqlite]
  # The options below are for mysql and postgresql only
  # host = "127.0.0.1"
  # database = "minicron"
  # username = "minicron"
  # password = "password"

# Alerting options
[alerts]
  [alerts.email]
  enabled = false
      [alerts.email.smtp]
      address = "localhost"
      port = 25

  [alerts.sms]
  enabled = false

  [alerts.pagerduty]
  enabled = false

  [alerts.aws_sns]
  enabled = false

  [alerts.slack]
  enabled = false
