# Test valid config file

# Global options
verbose = false
debug = false

# Client options
[client]
  [client.server]
  scheme = "http" # [http, https]
  host = "127.0.0.1"
  port = 9292
  path = "/"
  connect_timeout = 5
  inactivity_timeout = 5
  # CLI options
  [client.cli]
  mode = "line" # [line, char]
  dry_run = false
  pid_wait_timeout = 5
  [client.pusher]
  enabled = false
  encrypted = false # See: https://pusher.com/docs/client_api_guide/client_connect#encrypting-connections
  # app_id = "YOUR_PUSHER_APP_ID"
  # key = "YOUR_PUSHER_KEY"
  # secret = "YOUR_PUSHER_SECRET"

# Server options
[server]
host = "127.0.0.1"
port = 9292
path = "/"
pid_file = "/tmp/minicron.pid"
timezone = "UTC"
  [server.session]
  name = "minicron.session"
  domain = "127.0.0.1"
  path = "/"
  ttl = 86400
  secret = "change_me"
  [server.database]
  type = "sqlite" # [mysql, postgresql, sqlite]
  # The options below are for mysql and postgresql only
  # host = "127.0.0.1"
  # database = "minicron"
  # username = "minicron"
  # password = "password"
  [server.ssh]
  connect_timeout = 10

# Alerting options
[alerts]
  [alerts.email]
  enabled = false
      [alerts.email.smtp]
      address = "localhost"
      port = 25

  [alerts.sms]
  enabled = false

  [alerts.pagerduty]
  enabled = false

  [alerts.aws_sns]
  enabled = false

  [alerts.slack]
  enabled = false
